version: '3'
services:
  bd:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DMN-pec1
    volumes:
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - bd
    environment:
      DB_HOST: bd
      DB_NAME: DMN-pec1
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    ports:
      - "5001:5000"
    volumes:
      - ./frontend:/frontend

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
